title:            tonghs
description:      A web developer
url:              tonghs.com # Site url.
baseurl:          http://tonghs.com
signoff:          tonghs # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-42638070-1  # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Home
    url:          /
  - name:         Product
    url:          /product
    external:     true
  - name:         About
    url:          /about
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
